apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jk5xlvj3q-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jk5xlvj3q-java-springboot-gitops